# Generated by Django 3.1.1 on 2020-10-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('image', models.CharField(default='none', max_length=128)),
                ('category', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='auctions.category')),
            ],
        ),
    ]
