# Generated by Django 3.1.1 on 2020-10-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_ID', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listings')),
                ('user_ID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
