# Generated by Django 3.1.1 on 2020-10-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_userlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlisting',
            old_name='user_ID',
            new_name='user',
        ),
    ]
