# Generated by Django 3.1.1 on 2020-10-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201005_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlisting',
            old_name='listing_ID',
            new_name='listing',
        ),
    ]
