# Generated by Django 3.1.1 on 2020-10-09 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201007_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddingListing', to='auctions.listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddingUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
