# Generated by Django 3.1.1 on 2020-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='active',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
