# Generated by Django 3.1.1 on 2020-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
