# Generated by Django 3.1.1 on 2020-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
