# Generated by Django 3.1.1 on 2020-11-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network.user'),
            preserve_default=False,
        ),
    ]
