# Generated by Django 3.1.1 on 2020-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201117_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
