# Generated by Django 3.1.1 on 2020-12-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_likes',
        ),
    ]
